[package]
name = "tfvar-export"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.0"
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
